apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: prereq
  sources:
    - repoURL: https://github.com/jakelooker/k8s-config.git
      targetRevision: main
      path: apps/cert-manager/config
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
    - CreateNamespace=true 
