apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unifi-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: unifi
    server: https://kubernetes.default.svc
  project: network
  sources:
    - repoURL: https://github.com/jakelooker/k8s-config.git
      targetRevision: main
      path: apps/unifi/config
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
    - CreateNamespace=true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m    