apiVersion: apps/v1
kind: Deployment
metadata:
  name: myogg
  namespace: web
  labels:
    name: myogg
spec:
  replicas: 1
  selector:
    matchLabels:
      name: myogg
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: myogg
    spec:
      containers:
        - image: nginx-unprivileged:latest
          name: myogg
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: myogg
              readOnly: true
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
          securityContext:
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 2003
            runAsGroup: 2003
      restartPolicy: Always
      volumes:
        - name: myogg
          persistentVolumeClaim:
            claimName: myogg
