apiVersion: v1
kind: Service
metadata:
  labels:
    app: frigate
  name: frigate
  namespace: frigate
spec:
  ports:
    - name: http
      port: 8971
      targetPort: 8971
  selector:
    app: frigate
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frigate
  name: frigate-static
  namespace: frigate
  annotations:
    metallb.universe.tf/allow-shared-ip: frigate
spec:
  ports:
    - name: rtsp
      port: 8554
      targetPort: 8554
    - name: webrtc-tcp
      port: 8555
      targetPort: 8555
      protocol: TCP
  selector:
    app: frigate
  type: LoadBalancer
  loadBalancerIP: 192.168.50.110
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frigate
  name: frigate-static-udp
  namespace: frigate
  annotations:
    metallb.universe.tf/allow-shared-ip: frigate
spec:
  ports:
    - name: webrtc-udp
      port: 8555
      targetPort: 8555
      protocol: UDP
  selector:
    app: frigate
  type: LoadBalancer
  loadBalancerIP: 192.168.50.110