# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: frigate-media
#   namespace: frigate
# spec:
#   capacity:
#     storage: 900Gi
#   accessModes:
#     - ReadWriteMany
#   storageClassName: "local-path"
#   nfs:
#     server: 192.168.50.2
#     path: "/mnt/speed/noBackup/frigate"
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: frigate-media
#   namespace: frigate
# spec:
#   accessModes:
#     - ReadWriteMany
#   storageClassName: "local-path"
#   resources:
#     requests:
#       storage: 900Gi
#   volumeName: frigate-media
