# apiVersion: longhorn.io/v1beta2
# kind: RecurringJob
# metadata:
#   name: weekly
#   namespace: longhorn-system
# spec:
#   concurrency: 2
#   cron: 0 2 ? * MON
#   groups:
#   - default
#   labels: {}
#   name: weekly
#   parameters: {}
#   retain: 4
#   task: backup